---
- name: Recreate required output directories
  tags: [eos_cli_config_gen]
  delegate_to: localhost
  run_once: true
  block:
    - name: "Cleanup {{ role_documentation_dir }}"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}"
        state: absent
    - name: "Create {{ role_documentation_dir }}"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}"
        state: directory
        mode: 0775
    - name: "Create {{ role_documentation_dir }}"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}/inputs"
        state: directory
        mode: 0775
    - name: "Create {{ role_documentation_dir }}"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}/data_model"
        state: directory
        mode: 0775

- name: Output eos_cli_config_gen Documentation
  tags: [eos_cli_config_gen]
  ansible.builtin.template:
    src: avd_schema_documentation.j2
    dest: "{{ role_documentation_dir ~ '/' ~ documentation_file.filename ~ '.md'  }}"
    mode: 0664
  loop: "{{ lookup('arista.avd.convert_to_documentation_schema', role_name) }}"
  loop_control:
    loop_var: documentation_file
    label: "{{ documentation_file.filename }}"
