---
# This device should get BGP configured for VRF default since there are BGP peers for the device under the VRF.
# Notice that the node type l3spine does not have a default overlay or underlay routing protocol, so they will not contribute BGP.

type: l3spine

l3spine:
  defaults:
    # platform: 7280R
    bgp_as: 65001
    spanning_tree_mode: none
    loopback_ipv4_pool: 192.0.255.0/24
    uplink_ipv4_pool: 10.255.1.0/24
  nodes:
    - name: bgp-from-network-services
      id: 1
      mgmt_ip: 10.1.1.1/24

tenants:
  - name: TEST
    vrfs:
      - name: default
        vrf_id: 100
        address_families: []
        static_routes:
          - destination_address_prefix: 0.0.0.0
            gateway: 10.10.1.1
            nodes: [bgp-from-network-services]
        l3_interfaces:
          - interfaces:
              - Ethernet47
            ip_addresses:
              - 10.10.1.1/30
            nodes:
              - bgp-from-network-services
        bgp_peers:
          - ip_address: 10.10.1.2
            peer_group: MYPEERGROUP
            nodes: [bgp-from-network-services]
        bgp_peer_groups:
          - name: MYPEERGROUP
            remote_as: 65991
            next_hop_self: true
            bfd: true
