type: l2leaf
l2leaf:
  nodes:
    - name: source-interfaces
      id: 1
      mgmt_ip: 192.168.0.2/24
      inband_mgmt_ip: 10.20.30.40/24
      inband_mgmt_gateway: 10.20.30.1
      inband_mgmt_vrf: INBANDMGMT

source_interfaces:
  radius:
    mgmt_interface: true
    inband_mgmt_interface: true
