# Roles Defaults
# Root directory where to build output structure
root_dir: '{{ inventory_dir }}'

# Documentation folders
# Main documentation folder
documentation_dir_name: 'documentation'
documentation_dir: '{{ root_dir }}/{{ documentation_dir_name }}'

# Fabric documentation
fabric_dir_name: 'fabric'
fabric_dir: '{{ documentation_dir }}/{{ fabric_dir_name }}'

# AVD configurations output
# Main output directory
output_dir_name: 'intended'
output_dir: '{{ root_dir }}/{{ output_dir_name }}'

# Output for structured YAML files:
structured_dir_name: 'structured_configs'
structured_dir: '{{ output_dir }}/{{ structured_dir_name }}'

# Design variables
design:
  type: "l3ls-evpn"

# Infrastructure Elements Keys
# connected_endpoints_keys: "{{ default_connected_endpoints_keys[design.type] }}"

# network_services_keys:
#   - name: tenants

# node_type_keys: "{{ default_node_type_keys[design.type] }}"

templates: "{{ default_templates[design.type] }}"

avd_structured_config_file_format: "yml"

# Input Variable Validation
avd_data_conversion_mode: "debug"
avd_data_validation_mode: "warning"
