# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  fabric_numbering:
    description: Automatic assignment of numbers for settings like Node ID.
    type: dict
    keys:
      id:
        type: dict
        description: Assignement of Node ID.
        keys:
          algorithm:
            type: str
            valid_values:
              - pool_manager
            description: |-
              If set, IDs will be automatically assigned using the configured algorithm unless statically configured under the node settings.

              - "pool_manager" will activate the pool manager for ID pools.

                The pools are dynamically built and matched on the following device data:
                - `fabric_name`
                - `dc_name`
                - `pod_name`
                - `type`

                Note: This means changing any of these fields may renumber the devices!

                Each pool will assign the first available ID starting from 1.

                Stale entries will be reclaimed from each pool automatically after every run.
                A stale entry is an entry that was not accessed during the run.
          pools_file:
            type: str
            description: |-
              Path to file to use for storing ID pool data when using "pool_manager" as algorithm.
              By default the path is "intended/data/<fabric_name>-ids.yml".

              Note: Since the pool manager will remove stale entries after every run, each fabric should be using it's own file.
