# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  fabric_ip_addressing:
    type: dict
    description: |-
      Configuration of the builtin IP addressing logic. These settings may not apply when using custom templates.
    keys:
      mlag:
        type: dict
        keys:
          algorithm:
            type: str
            default: "first_id"
            description: |-
              This variable defines the Multi-chassis Link Aggregation (MLAG) algorithm used.
              Each MLAG link will have a /31 subnet with each subnet allocated from the relevant MLAG pool via a calculated offset.
              The offset is calculated using one of the following algorithms:
                - first_id: `(mlag_primary_id - 1) * 2` where `mlag_primary_id` is the ID of the first node defined under the node_group.
                  This allocation method will skip every other /31 subnet making it less space efficient than `odd_id`.
                - odd_id: `(odd_id - 1) / 2`. Requires the node_group to have a node with an odd ID and a node with an even ID.
                - same_subnet: the offset will always be zero.
                  This allocation method will cause every MLAG link to be addressed with the same /31 subnet.
            valid_values:
              - "first_id"
              - "odd_id"
              - "same_subnet"
      inband_mgmt_ip:
        type: dict
        description: |-
          Automatic assigment of `inband_mgmt_ip` unless it is statically configured under the node settings.

          For L2 devices, the `inband_mgmt_ip` will be automatically assigned from either the configured `inband_mgmt_subnet` or
          the subnet of the VLAN set with `inband_mgmt_vlan`. No IP will be assigned if no subnet is found.

          L3 devices are not supported for automatic assignment of `inband_mgmt_ip`.
        keys:
          algorithm:
            type: str
            default: id
            valid_values:
              - id
              - pool_manager
            description: |-
              The IP address assignment is calculated using one of the following algorithms:
              - id: Offset into the subnet with `node_id + <ips_reserved_for_gateways>`.
              - pool_manager: Activate the pool manager.

                The pools are dynamically built and matched on the following data:
                - Subnet from either the configured `inband_mgmt_subnet` or the subnet of the VLAN set with `inband_mgmt_vlan`
                - `inband_mgmt_vrf`
                - The VRF under which the `inband_mgmt_vlan` is configured.

                Note: This means changing any of these fields may renumber the devices!

                Each pool will assign the first available IP starting from `1 + <ips_reserved_for_gateways>`.

                Stale entries will be reclaimed from each pool automatically after every run.
                A stale entry is an entry that was not accessed during the run.
          ips_reserved_for_gateways:
            type: int
            default: 3
      pools_file:
        type: str
        description: |-
          Path to file to use for storing IP pool data when using "pool_manager" as algorithm.
          By default the path is "intended/data/<fabric_name>-ips.yml".

          Note: Since the pool manager will remove stale entries after every run, each fabric should be using it's own file.
