# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  pool_manager:
    description: Pool Manager used for automatic assignment of pool values.
    type: dict
    keys:
      activate:
        type: bool
        default: false
        description: |-
          Activate the pool manager for all supported pools.
          Can be overridden per pool.
      id:
        type: dict
        description: |-
          Automatic assignement of Node ID.

          The pools are dynamically built and matched on the following device data:
          - `fabric_name`
          - `dc_name`
          - `pod_name`
          - `type`
          Note: This means changing any of these fields may renumber the devices!

          Each pool will assign first available ID starting from 1.

          Stale entries will be removed from each pool automatically on every run.
          A stale entry is any entry not accessed during the run.
        keys:
          activate:
            type: bool
            description: |-
              Activate the pool manager for ID pools.
              Overrides the activation on pool manager.
          path:
            type: str
            description: |-
              Path to file to use for storing ID pool data.
              By default the path is "intended/data/<fabric_name>-ids.yml".

              Note: Since stale entries are removed per run, each fabric should be using it's own file.
