# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  pool_manager:
    description: Pool Manager used for automatic assignment of pool values.
    type: dict
    keys:
      activate:
        type: bool
        default: false
        description: |-
          Activate the pool manager for all supported pools.
          Can be overridden per pool.
      id:
        type: dict
        description: Automatic assignement of Node ID
        keys:
          activate:
            type: bool
            description: |-
              Activate the pool manager for ID pools.
              Overrides the activation on pool manager.
          path:
            type: str
            description: |-
              Path to file to use for storing ID pool data.
              By default the path is "intended/data/<fabric_name>-ids.yml".
