# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  sflow_settings:
    documentation_options:
      table: management-sflow-settings
    type: dict
    description: |-
      sFlow settings.
      The sFlow process will only be configured if any interface is enabled for sFlow.
      For default enabling of sFlow for various interface types across the fabric see "fabric_sflow"
    keys:
      destinations:
        type: list
        items:
          type: dict
          keys:
            destination:
              type: str
              required: true
              description: |-
                sFlow destination IP address.
            port:
              type: int
              description: Port number
              convert_types:
                - str
            vrf:
              required: true
              type: str
              description: |-
                The value of `vrf` will be interpreted according to these rules:
                - `use_mgmt_interface_vrf` will configure the sFlow destination under the VRF set with `mgmt_interface_vrf` and set the `mgmt_interface` as sFlow source-interface.
                  An error will be raised if `mgmt_ip` or `ipv6_mgmt_ip` are not configured for the device.
                - `use_inband_mgmt_vrf` will configure the NTP server(s) under the VRF set with `inband_mgmt_vrf` and set the `inband_mgmt_interface` as NTP source-interface.
                  An error will be raised if inband management is not configured for the device.
                - Any other string will be used directly as the VRF name but source interface must be set with `sflow.structured_config` as needed.
              convert_types:
                - int
      structured_config:
        type: dict
        description: Custom structured config added under sflow for eos_cli_config_gen
