# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  sflow_settings:
    documentation_options:
      table: management-sflow-settings
    type: dict
    description: |-
      sFlow settings.
      The sFlow process will only be configured if any interface is enabled for sFlow.
      For source-interfaces see "source_interfaces.sflow"
      For default enabling of sFlow for varous interface types across the fabric see "fabric_sflow"
    keys:
      destinations:
        type: list
        items:
          type: dict
          keys:
            destination:
              type: str
              required: true
              description: |-
                sFlow destination IP address.
            port:
              type: int
              description: Port number
              convert_types:
                - str
            vrf:
              type: str
              description: |-
                VRF Name.
                Can be used in combination with "use_mgmt_interface_vrf" and "use_inband_mgmt_vrf" to configure the destination under multiple VRFs.
              convert_types:
                - int
            use_mgmt_interface_vrf:
              type: bool
              description:
                Configure the destination under the VRF set with "mgmt_interface_vrf".
                Can be used in combination with "vrf" and "use_inband_mgmt_vrf" to configure the destination under multiple VRFs.
            use_inband_mgmt_vrf:
              type: bool
              description:
                Configure the destination under the VRF set with "inband_mgmt_vrf".
                Ignored if inband management is not configured for the device.
                Can be used in combination with "vrf" and "use_mgmt_interface_vrf" to configure the destination under multiple VRFs.
      structured_config:
        type: dict
        description: Custom structured config added under sflow for eos_cli_config_gen
