# Management API HTTP
management_api_http:
  enable_http: false
  enable_https: true
  https_ssl_profile: SSL_PROFILE
  default_services: true
  enable_vrfs:
    - name: default
      access_group: ACL-API
    - name: MGMT
      access_group: ACL-API
