# yaml-language-server: $schema=../../../../../../../development/schema.schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
underlay_routing_protocol:
  type: str
  valid_values:
    - "ebgp"
    - "ospf"
    - "isis"
    - "isis-sr"
    - "isis-ldp"
    - "isis-sr-ldp"
    - "ospf-ldp"
  case_sensitive: false
  default: "ebgp"

access_lists:
  type: list
  unique_keys:
    - name
  display_name: IP Extended Access-Lists
  description: |
    AVD currently supports 2 different data models for extended ACLs:

    - The legacy `access_lists` data model, for compatibility with existing deployments
    - The improved `ip_access_lists` data model, for access to more EOS features

    Both data models can coexists without conflicts, as different keys are used: `access_lists` vs `ip_access_lists`.
    Access list names must be unique.

    The legacy data model supports simplified ACL definition with `sequence_number` to `action_string` mapping:
  items:
    type: dict
    keys:
      name:
        type: str
        required: true
        display_name: access_list_name
      counters_per_entry:
        type: bool
      sequence_numbers:
        type: list
        required: true
        unique_keys:
          - sequence
        items:
          type: dict
          keys:
            sequence:
              type: int
              required: true
              display_name: sequence_id
            action:
              type: str
              required: true
              display_name: action as string
