# yaml-language-server: $schema=../../../../../../../development/schema.schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
evpn_ebgp_multihop:
  display_name: EVPN EBGP Multihop
  description: |
    Default of 3, the recommended value for a 3 stage spine and leaf topology.
    Set to a higher value to allow for very large and complex topologies.
  type: int
  default: 3
