# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
allow_other_keys: true
keys:
  p2p_uplinks_mtu:
    display_name: Point to Point Links MTU
    type: int
    default: 9000
