# Create Ansible Execution Environment - using minimum requirements - for use in CI workflows
# Run from root of repo
# Example:
#   ansible-builder build --container-runtime=docker --tag=ci-ee-minimum:<tag> --verbosity 3 -f .github/ansible_execution_environments/ci-ee-minimum.yml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.11-latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--force --verbose'

dependencies:
  galaxy: ../../ansible_collections/arista/avd/min-collections.yml
  python: ../../ansible_collections/arista/avd/min-requirements.txt
  system: ../../ansible_collections/arista/avd/bindep.txt
