# Create Ansible Execution Environment for use in CI workflows
# Run from root of repo
# Example:
#   ansible-builder build --container-runtime=docker --tag=ci-ee-latest:<tag> --verbosity 3 -f .github/ansible_execution_environments/ci-ee-latest.yml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--force --verbose'

dependencies:
  galaxy: ../../ansible_collections/arista/avd/collections.yml
  python: ../../ansible_collections/arista/avd/requirements.txt
  system: ../../ansible_collections/arista/avd/bindep.txt
