---
- name: Create AVD Studio package
  hosts: localhost
  gather_facts: false
  vars:
    pwd: "{{ lookup('env', 'PWD') }}"
    package_dir: "{{ pwd }}"
    studio_design_file: "{{ pwd ~ '/studio-design.yml' }}"
  tasks:
    - name: Build AVD Studio from Studio Design
      tags: [always, build]
      delegate_to: localhost
      arista.avd.build_studio_package:
        schema_id: "eos_designs"
        studio_design: "{{ lookup('file', studio_design_file) | from_yaml }}"
        package_dir: "{{ package_dir }}"
      register: build_studio_package

    - name: Set tar_archive var
      delegate_to: localhost
      set_fact:
        tar_archive: "{{ build_studio_package.package_id }}-{{ build_studio_package.package_version }}.tar"
        org_package_dir: "{{ package_dir }}"

    - name: Tar Studio package
      tags: [always, build]
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: "tar -cf {{ tar_archive }} {{ build_studio_package.package_id }}"
        chdir: "{{ package_dir }}"

- name: Upload avd-base package
  hosts: all
  gather_facts: false
  vars:
    tar_archive: "{{ hostvars.localhost.tar_archive }}"
    package_dir: "{{ hostvars.localhost.org_package_dir }}"
  tasks:
    - name: Upload avd-base package
      tags: [deploy]
      delegate_to: localhost
      ansible.builtin.shell:
        chdir: "{{ package_dir }}"
        cmd: >-
          curl -X 'POST' -k
          --cookie "access_token={{ ansible_password }}"
          -H 'accept: application/json'
          -H 'Content-Type: multipart/form-data'
          -F 'file=@{{tar_archive}};type=application/x-tar'
          https://{{ inventory_hostname }}/cvpservice/packaging/v1/packages
