hostname: bgp-from-network-services
is_deployed: true
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
transceiver_qsfp_default_mode_4x10: true
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 10.1.1.1/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.0.255.1/32
ip_igmp_snooping:
  globally_enabled: true
ethernet_interfaces:
- name: Ethernet47
  peer_type: l3_interface
  ip_address: 10.10.1.1/30
  shutdown: false
  type: routed
