router_bgp:
  as: '65002'
  router_id: 192.168.254.2
  bgp_defaults:
  - maximum-paths 4 ecmp 4
  peer_groups:
  - type: ipv4
    maximum_routes: 12000
    send_community: all
    name: IPv4-UNDERLAY-PEERS
  address_family_ipv4:
    peer_groups:
    - activate: true
      name: IPv4-UNDERLAY-PEERS
  redistribute_routes:
  - route_map: RM-CONN-2-BGP
    source_protocol: connected
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
loopback_interfaces:
- description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 192.168.254.2/32
  name: Loopback0
- description: VTEP_VXLAN_Tunnel_Source
  shutdown: false
  ip_address: 192.168.253.2/32
  name: Loopback1
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.254.0/24 eq 32
  - sequence: 20
    action: permit 192.168.253.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
management_cvx:
  source_interface: Loopback0
  server_hosts:
  - 192.168.254.254
  - 192.168.254.255
vlans:
- id: 2900
  name: L2VLAN_2900
  tenant: TEST
- id: 2901
  name: L2VLAN_2901
  tenant: TEST
ip_igmp_snooping:
  globally_enabled: true
vxlan_interface:
  Vxlan1:
    description: OVERLAY_ROUTING_PROTOCOL_CVX_L3LEAF2_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
      vlans:
      - id: 2900
        vni: 12900
      - id: 2901
        vni: 12901
