---

type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-LAB
    uplink_interfaces: [Ethernet1, Ethernet2]
    uplink_switches: [CUSTOM-TEMPLATES-L3LEAF1A, CUSTOM-TEMPLATES-L3LEAF1B]
  node_groups:
    - group: CUSTOM_TEMPLATES_L3LEAF1
      bgp_as: 65101
      nodes:
        - name: CUSTOM-TEMPLATES-L2LEAF1A
          id: 1
          mgmt_ip: 192.168.200.103/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5 ]
