---
type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-lab
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['sflow-tests-leaf3', 'sflow-tests-leaf4']
    inband_mgmt_subnet: "10.254.254.0/24"
  nodes:
    - name: sflow-tests-l2-leaf1
      id: 1
      mgmt_ip: 192.168.0.201/24
      uplink_switch_interfaces:
        - Ethernet16
        - Ethernet16


    - name: sflow-tests-l2-leaf2
      id: 2
      mgmt_ip: 192.168.0.202/24
      uplink_switch_interfaces:
        - Ethernet17
        - Ethernet17

# Overriding the global setting to get inband_mgmt for l2 leafs.
source_interfaces:
  sflow:
    mgmt_interface: true
    inband_mgmt_interface: true
