---
- name: Recreate required output directories
  tags: [eos_designs]
  delegate_to: localhost
  run_once: true
  block:
    - name: "Cleanup {{ role_documentation_dir }}"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}"
        state: absent
    - name: "Create {{ role_documentation_dir }}"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}"
        state: directory
        mode: 0775

- name: Output eos_designs Documentation
  tags: [eos_designs]
  ansible.builtin.template:
    src: avd_schema_documentation.j2
    dest: "{{ role_documentation_dir ~ '/' ~ filename ~ '.md'  }}"
    mode: 0664
  loop: "{{ documentation_schema | list }}"
  loop_control:
    loop_var: filename
  vars:
    documentation_schema: "{{ role_name | arista.avd.convert_schema(type='documentation') }}"
