---
- name: Create required output directories if not present
  tags: [build, provision]
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ structured_dir }}"
    - "{{ fabric_dir }}"
  delegate_to: localhost
  run_once: true

- name: Set AVD facts
  tags: [build, provision]
  yaml_templates_to_facts:
    templates: "{{ templates.facts }}"
  delegate_to: localhost
  check_mode: no
  changed_when: False

- name: Set AVD topology facts
  tags: [build, provision]
  yaml_templates_to_facts:
    templates: "{{ templates.topology_facts }}"
  delegate_to: localhost
  check_mode: no
  changed_when: False

- name: Generate YAML file with hostvars (only for debugging)
  tags: [debug, never]
  copy:
    content: "{{ hostvars[inventory_hostname] | to_nice_yaml(indent=2, sort_keys=False) }}"
    dest: "{{ structured_dir }}/{{ inventory_hostname }}-debug-vars.yml"
    mode: 0664
  delegate_to: localhost
  changed_when: False

- name: Generate device configuration in structured format
  tags: [build, provision]
  yaml_templates_to_facts:
    templates: "{{ templates.structured_config }}"
  delegate_to: localhost
  check_mode: no
  changed_when: False
  register: eos_designs_result

- name: Write device structured configuration to YAML file
  tags: [build, provision]
  copy:
    content: "{{ eos_designs_result.ansible_facts | to_nice_yaml(indent=2, sort_keys=False) }}"
    dest: "{{ structured_dir }}/{{ inventory_hostname }}.yml"
    mode: 0664
  delegate_to: localhost
  changed_when: False
  when: eos_designs_result.ansible_facts is defined

- name: Generate fabric documentation
  tags: [build, provision, documentation]
  run_once: true
  delegate_to: localhost
  check_mode: no
  copy:
    content: "{{ lookup('template','fabric-documentation.j2') | arista.avd.add_md_toc(skip_lines=3) }}"
    dest: "{{ fabric_dir }}/{{ fabric_name }}-documentation.md"
    mode: 0664


- name: Generate fabric point-to-point links summary in csv format.
  tags: [build, provision, documentation]
  template:
    src: documentation/fabric-p2p-links.j2
    dest: "{{ fabric_dir }}/{{ fabric_name }}-p2p-links.csv"
    mode: 0664
  delegate_to: localhost
  run_once: true
  check_mode: no

- name: Generate fabric topology in csv format.
  tags: [build, provision, documentation]
  template:
    src: documentation/fabric-topology.j2
    dest: "{{ fabric_dir }}/{{ fabric_name }}-topology.csv"
    mode: 0664
  delegate_to: localhost
  run_once: true
  check_mode: no
