[package]
name = "pyavd-rust"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
name = "_rust"
crate-type = ["cdylib"]

[dependencies]
avdschema = { git = "https://github.com/ClausHolbechArista/pyavd-utils", rev = "d67e138", default-features = false, features = ["mmap"] }
pyo3 = { version = "0.29.0", features = ["abi3-py310"] }
serde = "1.0.229"
serde_json = "1.0.150"
validation = { git = "https://github.com/ClausHolbechArista/pyavd-utils", rev = "d67e138", default-features = false, features = ["archive", "regex-perf"] }
