name: "Pull Request Comment"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ###################################################
  # Add comment with useful links for the reviewers
  ###################################################

  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          BODY: |
            Review docs on [Read the Docs](https://ansible-avd--${{ github.event.pull_request.number }}.org.readthedocs.build/en/${{ github.event.pull_request.number }}/)

            To test this pull request:

            ```sh
            # Create virtual environment for this testing below the current directory
            python -m venv test-avd-pr-${{ github.event.pull_request.number }}
            # Activate the virtual environment
            source test-avd-pr-${{ github.event.pull_request.number }}/bin/activate
            # Install all requirements including PyAVD
            pip install "pyavd[ansible] @ git+${{ github.event.pull_request.head.clone_url }}@${{ github.event.pull_request.head.ref }}#subdirectory=python-avd" --force
            # Install Ansible collection
            ansible-galaxy collection install git+${{ github.event.pull_request.head.clone_url }}#/ansible_collections/arista/avd/,${{ github.event.pull_request.head.ref }} --force
            # Optional: Install AVD examples
            cd test-avd-pr-${{ github.event.pull_request.number }}
            ansible-playbook arista.avd.install_examples
            ```
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ BODY }}
            })
