### VLAN Interfaces ###

# Testing vlan_interfaces as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
vlan_interfaces:
  Vlan1:
    description: test ipv6_address_virtual
    ipv6_enable: true
    # Testing ipv6_address_virtual alone
    # ipv6_address_virtual deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_address_virtual: fc00:10:10:1::1/64

  Vlan2:
    description: test ipv6_address_virtual and ipv6_address_virtuals
    ipv6_enable: true
    # Testing ipv6_address_virtual in combination with the new ipv6_address_virtuals to see that all three are configured
    # ipv6_address_virtual deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_address_virtual: fc00:10:10:2::1/64
    ipv6_address_virtuals:
      - fc00:10:11:2::1/64
      - fc00:10:12:2::1/64
